import Head from "next/head";
import React from "react";
import Slider from "../components/slider/Slider";
import styles from "../styles/Home.module.css";
import TShrits from "./tShrits";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Slider />
        <TShrits />
      </main>
    </div>
  );
}
